CREATE TABLE `hos`.`clinic` (
	`clinic` CHAR(3) NOT NULL DEFAULT '' COLLATE 'tis620_thai_ci',
	`name` VARCHAR(150) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`labparam` VARCHAR(10) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`icd10` VARCHAR(6) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`chronic` CHAR(1) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`clinic_guid` VARCHAR(38) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`pcu_code` INT(11) NULL DEFAULT NULL,
	`oapp_activity_id` VARCHAR(5) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`disable_dialog` CHAR(1) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`no_export` CHAR(1) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`active_status` CHAR(1) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`hosxp_clinic_type_id` INT(11) NULL DEFAULT NULL,
	`online_register_type_id` INT(11) NULL DEFAULT NULL,
	`online_ncd_segment_id` VARCHAR(50) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`online_ncd_key` VARCHAR(50) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`ncd` CHAR(1) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`depcode` VARCHAR(3) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`location` VARCHAR(200) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`phone` VARCHAR(50) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`oldcode` VARCHAR(20) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`open_time` TIME NULL DEFAULT NULL,
	`close_time` TIME NULL DEFAULT NULL,
	`app_limit_qty` INT(11) NULL DEFAULT NULL,
	`limit_access` CHAR(1) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`sss_clinic_code` CHAR(3) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`use_app_qs_slot` CHAR(1) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`queue_prefix` VARCHAR(5) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	`kiosk_opd_qs_room_id` INT(11) NULL DEFAULT NULL,
	`opd_kios_dep_menu_id` INT(11) NULL DEFAULT NULL,
	`opd_qs_schedule_tmpl_type_id` INT(11) NULL DEFAULT NULL,
	`moph_vaccine_ncd_id` INT(11) NULL DEFAULT NULL,
	`phr_skip` CHAR(1) NULL DEFAULT NULL COLLATE 'tis620_thai_ci',
	PRIMARY KEY (`clinic`) USING BTREE,
	INDEX `ix_name` (`name`) USING BTREE,
	INDEX `ix_clinic_guid` (`clinic_guid`) USING BTREE,
	INDEX `ix_sss_clinic_code` (`sss_clinic_code`) USING BTREE
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;
